version: '2'
services:
    lotrlcg-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/lotrlcg/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=lotrlcg
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
